"""defoult

Revision ID: 2bb0b38988bb
Revises: 
Create Date: 2023-10-01 15:21:02.628532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bb0b38988bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.Column('unique_param', sa.String(length=100), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('country', sa.String(length=56), nullable=False),
    sa.Column('adress', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('unique_param')
    )
    op.create_table('dangerous_types',
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recipients',
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.Column('customs_address', sa.String(length=1024), nullable=True),
    sa.Column('adress', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('senders',
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.Column('customs_address', sa.String(length=1024), nullable=True),
    sa.Column('adress', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cargoes',
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('ldm', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('arrival', sa.Date(), nullable=True),
    sa.Column('departure', sa.Date(), nullable=True),
    sa.Column('temperature_celsius', sa.Integer(), nullable=True),
    sa.Column('auto_in_number', sa.String(length=200), nullable=True),
    sa.Column('auto_out_number', sa.String(length=200), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['senders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.Column('email', sa.String(length=1024), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('password_hashed', sa.LargeBinary(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cargoes_dangerous_types',
    sa.Column('cargo_id', sa.Integer(), nullable=False),
    sa.Column('dangerous_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dangerous_type_id'], ['dangerous_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cargo_id', 'dangerous_type_id')
    )
    op.create_table('users_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_roles')
    op.drop_table('cargoes_dangerous_types')
    op.drop_table('users')
    op.drop_table('cargoes')
    op.drop_table('senders')
    op.drop_table('roles')
    op.drop_table('recipients')
    op.drop_table('dangerous_types')
    op.drop_table('clients')
    # ### end Alembic commands ###
