"""chweck

Revision ID: 4d4c0ca94064
Revises: 0434ace95995
Create Date: 2023-09-29 15:31:40.388108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d4c0ca94064'
down_revision: Union[str, None] = '0434ace95995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cargoes', sa.Column('sender_id', sa.Integer(), nullable=False))
    op.add_column('cargoes', sa.Column('recipient_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cargoes', 'clients', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cargoes', 'clients', ['recipient_id'], ['id'], ondelete='CASCADE')
    op.drop_column('clients', 'senders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('senders', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cargoes', type_='foreignkey')
    op.drop_constraint(None, 'cargoes', type_='foreignkey')
    op.drop_column('cargoes', 'recipient_id')
    op.drop_column('cargoes', 'sender_id')
    # ### end Alembic commands ###
