"""defoult

Revision ID: 8aa0eecbb2a1
Revises: 4d4c0ca94064
Create Date: 2023-09-30 15:00:08.542172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa0eecbb2a1'
down_revision: Union[str, None] = '4d4c0ca94064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
