"""defoult

Revision ID: bc8c3bf41656
Revises: 8aa0eecbb2a1
Create Date: 2023-09-30 15:41:10.008986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc8c3bf41656'
down_revision: Union[str, None] = '8aa0eecbb2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipients_clients')
    op.drop_table('senders_clients')
    op.add_column('clients', sa.Column('senders', sa.String(length=1024), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'senders')
    op.create_table('senders_clients',
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='senders_clients_client_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['senders.id'], name='senders_clients_sender_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sender_id', 'client_id', name='senders_clients_pkey')
    )
    op.create_table('recipients_clients',
    sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='recipients_clients_client_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], name='recipients_clients_recipient_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipient_id', 'client_id', name='recipients_clients_pkey')
    )
    # ### end Alembic commands ###
